spring:
  profiles:
    active: dev
---

server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.MrLQQ.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: password
    username: root

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
  instance:
    instance-id: springcloud-provider-dept-8001   # 修改默认描述
    prefer-ip-address: true

# info配置
info:
  app.name: MrLQQ-springcloud
  company.name: blog.MrLQQ.com
  
  ---

server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.MrLQQ.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: password
    username: root

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    fetch-registry: true
  instance:
    instance-id: springcloud-provider-dept-8001   # 修改默认描述
    prefer-ip-address: true

# info配置
info:
  app.name: MrLQQ-springcloud
  company.name: blog.MrLQQ.com
